// All actions possible in this app

export const COMMENTS_FETCH = 'COMMENTS_FETCH';
export const COMMENTS_INVALIDATE = 'COMMENTS_INVALIDATE';
export const COMMENTS_RECEIVE = 'COMMENTS_RECEIVE';
export const NAVIGATION_FETCH = 'NAVIGATION_FETCH';
export const NAVIGATION_INVALIDATE = 'NAVIGATION_INVALIDATE';
export const NAVIGATION_RECEIVE = 'NAVIGATION_RECEIVE';
export const POSTS_FETCH = 'POSTS_FETCH';
export const POSTS_INVALIDATE = 'POSTS_INVALIDATE';
export const POSTS_RECEIVE = 'POSTS_RECEIVE';
export const TERMS_FETCH = 'TERMS_FETCH';
export const TERMS_INVALIDATE = 'TERMS_INVALIDATE';
export const TERMS_RECEIVE = 'TERMS_RECEIVE';
