// Fetching navigation, posts, terms, comments.
// API actions are prefixed with API. UI actions are prefixed with UI.
// Commented out actions haven't been implemented yet.

export const POST_REQUEST = 'POST_REQUEST';
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
export const POST_REQUEST_FAILURE = 'POST_REQUEST_FAILURE';

export const POSTS_RECEIVE = 'POSTS_RECEIVE';
export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';
export const POSTS_REQUEST_FAILURE = 'POSTS_REQUEST_FAILURE';

export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_REQUEST_SUCCESS = 'PAGE_REQUEST_SUCCESS';
export const PAGE_REQUEST_FAILURE = 'PAGE_REQUEST_FAILURE';
export const PAGE_RECEIVE = 'PAGE_RECEIVE';

export const TERM_REQUEST = 'TERM_REQUEST';
export const TERM_REQUEST_SUCCESS = 'TERM_REQUEST_SUCCESS';
export const TERM_REQUEST_FAILURE = 'TERM_REQUEST_FAILURE';
export const TERM_RECEIVE = 'TERM_RECEIVE';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';
export const COMMENTS_REQUEST_FAILURE = 'COMMENTS_REQUEST_FAILURE';
export const COMMENTS_RECEIVE = 'COMMENTS_RECEIVE';
